[package]
name = "imgcmp"
version = "0.1.0"
authors = ["Dan Kaplun <dbkaplun@gmail.com>"]

[dependencies]
image = { git = "https://github.com/PistonDevelopers/image", rev = "89c6c5f" }
num-traits = "*"
